# to help GitHub realize it's a Jekyll site
#theme: jekyll-theme-minimal # for styling (Clean, simple, and great for blogs)
theme: jekyll-theme-cayman #(Modern, bold headers with a blue/green gradient)
#theme: jekyll-theme-hacker (Dark mode, monospaced font)
#theme: jekyll-theme-slate # (Dark, professional look)